// 前端表单默认参数
export const defaultForm = {
  base_config: {
    num_students: 200,
    num_schools: 3,
    num_employers: 20,
    num_majors: 4,
    num_job_types: 8,
    steps: 5,
    random_seed: 42,
  },
  student_config: {
    interest_weight: 0.3,
    salary_weight: 0.2,
    major_weight: 0.3,
    city_weight: 0.1,
    market_signal_weight: 0.1,
    cross_major_acceptance: 0.7,
    information_transparency: 0.8,
    max_applications_per_step: 3,
  },
  school_config: {
    training_quality: 0.7,
    capacity_adjust_speed: 0.1,
    employment_feedback_weight: 0.6,
    market_feedback_weight: 0.4,
    adjustment_lag: 1,
    resource_support: 0.03,
  },
  employer_config: {
    major_preference_strength: 0.8,
    skill_preference_strength: 0.9,
    hire_threshold: 0.55,
    cross_major_tolerance: 0.6,
    salary_elasticity: 0.05,
    threshold_relax_speed: 0.03,
    tolerance_increase_speed: 0.03,
  },
  scenario_config: {
    macro_economy: 1.0,
    policy_support: 0.5,
    industry_boom_factor: 1.0,
    market_heat_amplification: 1.0,
    city_attractiveness_gap: 0.5,
    technology_change_rate: 0.2,
    information_shock: 0.0,
    enterprise_feedback_lag: 2,
    school_feedback_lag: 4,
  },
  type_config: {
    employment_oriented_ratio: 0.3,
    interest_oriented_ratio: 0.25,
    prestige_oriented_ratio: 0.2,
    trend_sensitive_ratio: 0.25,

    research_university_ratio: 0.2,
    applied_university_ratio: 0.5,
    vocational_college_ratio: 0.3,

    tech_strict_ratio: 0.25,
    growth_firm_ratio: 0.3,
    traditional_firm_ratio: 0.25,
    cost_sensitive_ratio: 0.2,
  },
  data_config: {
    data_mode: "database",
    use_census_distribution: true,
    auto_generate_missing_data: true,
    student_data_path: "",
    school_data_path: "",
    employer_data_path: "",
    major_data_path: "",
    job_data_path: "",
  },
  llm_config: {
    enabled: true,
    use_for_profile_generation: false,
    use_for_scenario_generation: true,
    use_for_result_explanation: true,
    use_for_report_generation: true,
    model_name: "qwen-plus",
    temperature: 0.3,
    max_tokens: 1500,
  },
};